### ISSUE TITLE
"now" is written as "know" throughout docs

### ISSUE THREAD

**Issue by Erudition** [dao-xyz/peerbit#143]
In various markdown files in this repo, the word "now" is written as "know" for some reason. Yes, this is a minor nitpick, just thought it'd be helpful to create an issue.

Most of the time it's this phrase:
`as of know,`
which presumably is intended to mean
`as of now,`
given the contexts it's used in.

**Comment by marcus-pousette** [comment]
Thanks for creating this issue!

I think the all docs need to be sent through a grammar check.

**Comment by marcus-pousette** [comment]
Most typos fixed in https://github.com/dao-xyz/peerbit/commit/d6192163bb37026ea19aa48118a024fc426111bd

**Comment by Erudition** [comment]
Great edits, but you didn't fix any of the typos that this issue is about.
I'll start a pull request.

**Comment by Erudition** [comment]
PR opened, #167 !
